version: 2
jobs:
  one:
    docker:
      - image: circleci/node:carbon
    steps:
      - checkout
      - run: echo "--> testing <--"
      - run: sleep 25
  two:
    docker:
      - image: circleci/node:carbon
    steps:
      - checkout
      - run: echo "hello"
      - run: sleep 15
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
